# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2025-02-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181030_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='valor',
            name='fecha_dispositivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
