# Generated by Django 2.2.28 on 2025-05-28 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_valor_fecha_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='sensor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Sensor'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='dispositivo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='valor',
            name='campo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Campo'),
        ),
    ]
