# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-30 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20250528_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaDeValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_minimo', models.FloatField()),
                ('valor_maximo', models.FloatField()),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='dashboard.EscalaDeValor')),
            ],
        ),
    ]
