# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-05-31 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_escaladevalor_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='rango',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
