# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rango_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaladevalor',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.Sensor'),
        ),
    ]
