# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_escaladevalor_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaladevalor',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='dashboard.Sensor'),
        ),
    ]
